name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the issue
      placeholder: |
        1. Create a TDuckFrame with...
        2. Call method...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that demonstrates the issue
      render: pascal
      placeholder: |
        var
          DB: TDuckDBConnection;
          Frame: TDuckFrame;
        begin
          // Your code here
        end;
    validations:
      required: false

  - type: dropdown
    id: version
    attributes:
      label: DuckDB Version
      description: What version of DuckDB are you using?
      options:
        - 1.3.2
        - 1.3.1
        - 1.3.0
        - 1.2.x
        - 1.1.x
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: fpc-version
    attributes:
      label: FreePascal Version
      description: What version of FreePascal are you using?
      options:
        - 3.2.2
        - 3.2.0
        - 3.0.4
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - Linux (Ubuntu)
        - Linux (Other)
        - macOS
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: error-message
    attributes:
      label: Error Message
      description: If applicable, please provide the full error message
      render: text
      placeholder: Paste the complete error message here
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might help us understand the issue
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
